[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "lapy >= 0.6, < 0.7",
    "numpy >= 1.14",
    "setuptools>=42",
    "wheel",
]


[project]
name = "neuroshape"
version = "0.0.4.6.5"
description = "For computing connectopic and geometric Laplacian eigenmodes and performing null hypothesis testing. As implementation is ongoing, this description is subject to rapid change."
readme = "README.rst"
authors = [
    {name = "Nikitas C. Koussis", email = "nikitas.koussis@gmail.com"},
]
license = { file = "LICENSE" }

[project.urls]
Source = "https://github.com/nikitas-k/neuroshape-dev"
Documentation = "https://github.com/nikitas-k/neuroshape-dev"
